version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: curtain-mysql
    restart: always
    environment:
      MYSQL_DATABASE: curtain_db
      MYSQL_USER: curtain_user
      MYSQL_PASSWORD: curtain_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-app:
    build: .
    container_name: curtain-backend
    ports:
      - "9090:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/curtain_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: curtain_user
      SPRING_DATASOURCE_PASSWORD: curtain_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

volumes:
  mysql_data:
